=== Acubed/magnode/setup/mongodb/schema/DocumentRegion.json
{ "_id": {"$ObjectId": "5096739d5f7c227a6bbcae3c"}
, "id": "http://magnode.org/DocumentRegion"
, "subject": "http://magnode.org/DocumentRegion"
, "put": {"insertRevision":"revision", "storeResource":"documentregion"}
, "label": "DocumentRegion"
, "description": "A region of a document where content may be placed"
, "menu":
	{ "http://localhost/Menu_SettingsMenu":
		{ "title": "Document Regions"
		, "weight": 0
		}
	}
, "$schema": "http://json-schema.org/draft-04/schema#"
, "type": "object"
, "properties":
	{ "_id":
		{ "type": "ObjectId"
		, "readonly": true
		}
	, "_parent":
		{ "type": "ObjectId"
		, "readonly": true
		}
	, "subject":
		{ "type": "string"
		, "format": "uri"
		}
	, "type":
		{ "type": "array"
		, "widget": "http://magnode.org/field/Taxonomy"
		, "items": { "type": "string", "format": "uri" }
		, "taxonomySources":
			[
				{ "taxonomyFilter": "http://magnode.org/MongoDBJSONSchema"
				, "type": "string"
				, "label": "Schema"
				, "format": "uri"
				, "widget": "http://magnode.org/field/selectresource"
				, "range": "http://magnode.org/MongoDBJSONSchema"
				, "selectLabel": "label"
				, "selectNull": true
				, "undefinedIf": ["",null]
				, "default": ""
				}
			,
				{ "taxonomyFilter": "http://magnode.org/PublishOption"
				, "type": "array"
				, "label": "Publishing Options"
				, "format": "uri"
				, "widget": "http://magnode.org/field/selectresource"
				, "range": "http://magnode.org/PublishOption"
				, "selectLabel": "label"
				, "selectMulti": "checkbox"
				}
			]
		}
	, "label":
		{ "type": "string"
		, "widget": "http://magnode.org/field/Label"
		}
	, "blocks":
		{ "type": "array"
		, "widget": "array"
		, "items": { "type":"string", "format":"uri", "range":"http://magnode.org/Block" }
		, "description": "The block to be rendered out"
		}
	}
}

=== Acubed/magnode/setup/mongodb/documentregion/panel.json
{ "_id": {"$ObjectId": "50967e93cb6d3c9dbc8f5c60"}
,  "subject": "http://localhost/about#theme/twentyonetwelve/DocumentRegion_Panel"
, "type": ["http://magnode.org/DocumentRegion", "http://magnode.org/theme/twentyonetwelve/DocumentRegion_Panel"]
, "label": "Panel"
, "blocks": ["http://localhost/Menu_MainMenu", "http://localhost/Menu_ManagementMenu", "http://localhost/Menu_SettingsMenu"]
}
