=== Acubed/magnode/setup/mongodb/schema/Usergroup.json
{ "_id": {"$ObjectId": "4fe329bcf23943e90b000001"}
, "id": "http://magnode.org/Usergroup"
, "collection": "group"
, "label": "Privledged User Group"
, "description": "A group to which users may belong, possibly giving them permissions/authorizations"
, "menu":
	{ "http://localhost/Menu_ManagementMenu": {"weight": 0}
	}
, "put":
	{ "insertRevision": "revision"
	, "storeResource": "group"
	}
, "tablequery": {"fields": ["_id","subject", "label"]}
, "$schema": "http://json-schema.org/draft-04/schema#"
, "type": "object"
, "links":
	[ {"rel":"type", "href":"http://magnode.org/Usergroup"}
	]
, "default": []
, "properties":
	{ "_id": { "instance": "ObjectId", "readonly": true }
	, "subject": { "type": "string", "format": "uri" }
	, "type":
		{ "type": "array"
		, "widget": "http://magnode.org/field/Taxonomy"
		, "items": { "type": "string", "format": "uri" }
		, "taxonomySources":
			[
				{ "taxonomyFilter": "http://magnode.org/MongoDBJSONSchema"
				, "type": "array"
				, "label": "Schema"
				, "format": "uri"
				, "widget": "http://magnode.org/field/selectresource"
				, "range": "http://magnode.org/MongoDBJSONSchema"
				, "selectLabel": "label"
				, "selectNull": true
				, "undefinedIf": ["",null]
				, "default": ""
				}
			,
				{ "taxonomyFilter": "http://magnode.org/PublishOption"
				, "type": "array"
				, "label": "Publishing Options"
				, "format": "uri"
				, "widget": "http://magnode.org/field/selectresource"
				, "range": "http://magnode.org/PublishOption"
				, "selectLabel": "label"
				, "selectMulti": "checkbox"
				}
			]
		}
	, "label": { "type": "string", "widget": "http://magnode.org/field/Label"}
	, "grant":
		{ "type": "array"
		, "widget": "http://magnode.org/field/array"
		, "description": "The permissions being granted to this user"
		, "items":
			{ "type": "object"
			, "properties":
				{ "type":
					{ "type": "array"
					, "label": "Types"
					, "description": "Grant permissions to resources with all the specified types"
					, "default": []
					, "items": {"type": "string", "format": "uri"}
					, "widget": "http://magnode.org/field/Taxonomy"
					, "taxonomySources":
						[
							{ "taxonomyFilter": "http://magnode.org/MongoDBJSONSchema"
							, "type": "array"
							, "label": "Schema"
							, "format": "uri"
							, "widget": "http://magnode.org/field/selectresource"
							, "range": "http://magnode.org/MongoDBJSONSchema"
							, "selectLabel": "label"
							, "selectMulti": "checkbox"
							}
						,
							{ "taxonomyFilter": "http://magnode.org/PublishOption"
							, "type": "array"
							, "label": "Publishing Options"
							, "format": "uri"
							, "widget": "http://magnode.org/field/selectresource"
							, "range": "http://magnode.org/PublishOption"
							, "selectLabel": "label"
							, "selectMulti": "checkbox"
							}
						]
					}
				, "where":
					{ "type": "array"
					, "label": "Conditions"
					, "description": "Additional filters on which resources the grant applies to"
					, "default": []
					, "items": {"type": "string"}
					}
				, "action":
					{ "type": "array"
					, "label": "Granted Actions"
					, "description": "List of actions to be authorized"
					, "items": {"type": "string"}
					, "default": []
					}
				}
			, "default": {"type": [], "where": [], "action": []}
			, "additionalProperties": false
			}
		}
	}
}

=== Acubed/magnode/setup/mongodb/group/administrator.json
{ "_id": {"$ObjectId":"51b643d7e1b142bcff7f8e21"}
, "subject": "http://localhost/Usergroup/Administrator"
, "type": ["http://magnode.org/Usergroup"]
, "label": "Administrator"
, "grant":
	[
		{ "type": []
		, "where": []
		, "action": ["get", "view", "edit", "post", "put", "delete", "parse", "displayLinkMenu", "calculate-shadow"]
		}
	]
}

=== Acubed/magnode/setup/mongodb/group/author.json
{ "_id": {"$ObjectId":"51b64408e1b142bcff7f8e22"}
, "subject": "http://localhost/Usergroup/Author"
, "type": ["http://magnode.org/Usergroup"]
, "label": "Author"
, "grant":
	[
		{ "type": ["http://magnode.org/Post"]
		, "where": []
		, "action": ["get", "view", "edit", "post", "put", "delete", "parse"]
		}
	,
		{ "type": ["http://magnode.org/Page"]
		, "where": []
		, "action": ["get", "view", "edit", "post", "put", "delete", "parse"]
		}
	]
}
